### ISSUE TITLE
APIC packages  version

### ISSUE THREAD

**Issue by amikha33** [jtarte/mesh-apic-demo#1]
kindly which version of npm contains the option?

      --realm $REALM

**Comment by jtarte** [comment]
Hi @aghapy-mikhail 

I don't recall the exact version of APIC I used on this demo. This repo was made 2 yard ago. 
I used the APIC version that was available at this time. 
As far I remember, It  was APIC v10. but I don't remember the minor version.

**Comment by amikha33** [comment]
Thank you so much :)
